blank_issues_enabled: false
contact_links:
  - name: kendryte 官网
    url: https://canaan-creative.com/
    about: 了解kendryte系列
  - name: kendryte 开发者社区
    url: https://developer.canaan-creative.com/index.html?channel=developer#/home/0
    about: 您也可以在这里发帖讨论
  - name: kendryte 淘宝
    url: https://item.taobao.com/item.htm?spm=a230r.1.14.1.22714815bDh5ei&id=673510674381&ns=1&abbucket=0&mt=
    about: K510 CRB KIT 购买链接
